name: admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <3.2.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

  #business_logic:
  neo_core:
    git:
      url: https://github.com/amorphie/flutter.core
      ref: 0.0.69
  equatable: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.1.2
  http: ^0.13.5
  intl: ^0.18.1
  signalr_netcore: ^1.3.4
  logging: ^1.2.0
  url_launcher: ^6.1.12
  flutter_dotenv: ^5.1.0
  uuid: ^3.0.7
  device_info_plus: ^9.1.0

  #business_widgets
  flutter_bloc: ^8.1.3
  get: ^4.6.5
  webviewx: ^0.2.2
  json_dynamic_widget: ^7.0.5+1
  syncfusion_flutter_pdfviewer: ^20.4.54
  fl_chart: ^0.63.0
  json_annotation: ^4.8.1
  widgetbook: ^3.3.0
  widgetbook_annotation: ^3.0.0

  #widgets
  google_fonts: ^4.0.3
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  flutter_spinkit: ^5.2.0
  mask_text_input_formatter: ^2.5.0
  data_table_2: ^2.5.9
  lottie: ^2.7.0
  image_picker: ^1.0.5
  flutter_svg: ^2.0.9

dependency_overrides:
  uuid: ^4.1.0
  device_info_plus: ^9.1.0

dev_dependencies:
  logger: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  json_dynamic_widget_codegen: ^1.0.4
  json_serializable: ^6.7.1
  widgetbook_generator: ^3.2.0
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/settings/
    - assets/icons/
