name: admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  animated_splash_screen: ^1.3.0
  get: ^4.6.5
  page_transition: ^2.0.9
  http: ^0.13.5
  webviewx: ^0.2.2
  json_dynamic_widget: ^6.0.4+4
  uuid: ^3.0.7
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.3

dev_dependencies:
  logger: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
