name: admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  neo_core:
    git:
      url: https://github.com/amorphie/flutter.core
      ref: 0.0.29
  burgan_ui:
    git:
      url: https://github.com/amorphie/flutter.ui
      ref: 0.0.5
  cupertino_icons: ^1.0.3

  animated_splash_screen: ^1.3.0
  get: ^4.6.5
  page_transition: ^2.0.9
  http: ^0.13.5
  webviewx: ^0.2.2
  json_dynamic_widget: ^7.0.5+1
  uuid: ^3.0.7
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.2.0
  flutter_quill: ^7.2.4
  intl: ^0.18.1
  signalr_netcore: ^1.3.4
  logging: ^1.2.0
  url_launcher: ^6.1.12
  mask_text_input_formatter: ^2.5.0
  fl_chart: ^0.63.0
  syncfusion_flutter_pdfviewer: ^20.4.54
  flutter_dotenv: ^5.1.0

dependency_overrides:
  uuid: ^3.0.4
  device_info_plus: ^9.1.0

dev_dependencies:
  logger: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  json_dynamic_widget_codegen: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/icons/
