name: admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  google_fonts: ^2.1.0
  provider: ^5.0.0
  multilevel_drawer: ^2.0.0
  hovering: ^1.0.4
  context_menus: ^1.0.2
  flutter_screenutil: ^5.6.1
  get: ^4.6.5
  multi_select_flutter: ^4.1.3

dev_dependencies:
  logger: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
