name: backoffice
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  neo_core:
    git:
      url: https://github.com/amorphie/flutter.core
      ref: 0.0.98
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  uuid: # DO NOT SET. It's coming from neo_core project
  meta: ^1.10.0
  flutter_secure_storage: # DO NOT SET. It's coming from neo_core project
  http: # DO NOT SET. It's coming from neo_core project
  universal_io: # DO NOT SET. It's coming from neo_core project
  device_info_plus: # DO NOT SET. It's coming from neo_core project

  # UI Related
  flutter_svg: 2.0.9
  skeletonizer: ^1.0.1
  lottie: ^2.7.0
  flutter_pdfview: ^1.3.2
  flutter_native_splash: ^2.3.9
  fluttertoast: ^8.2.4

  # Dynamic Widget Building
  json_dynamic_widget: ^7.0.5+1
  child_builder: ^2.0.1

  # Deep link
  app_links: ^3.4.5

  # DI
  get_it: ^7.6.0
  injectable: ^2.1.2

  # Widgetbook for desktop app to demonstrate widgets
  widgetbook: ^3.3.0
  widgetbook_annotation: ^3.0.0

  # Utility
  collection: ^1.17.1
  expressions: ^0.2.5+1
  image_picker: ^1.0.5
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  system_proxy: 0.1.0
  async: ^2.11.0
  intl: # DO NOT SET. It's coming from neo_core project
  permission_handler: ^11.1.0
  webview_flutter: ^4.5.0

  # Backoffice
  syncfusion_flutter_pdfviewer: ^20.4.54
  data_table_2: ^2.5.9
  flutter_dotenv: ^5.1.0
  webviewx_plus: ^0.3.3
  json_path: ^0.6.6
  
dependency_overrides:
  uuid: ^4.1.0 # Delete this overrides when signalr_netcore package in neo_core package is updated
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  json_dynamic_widget_codegen: ^1.0.0
  flutter_launcher_icons: ^0.13.1


flutter:

  uses-material-design: true


  assets:
    - .env
    - assets/images/
    - assets/json/
    - assets/fonts/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
