import 'package:backoffice/util/neo_util.dart';

// TODO: Order enum values alphabetically to prevent possible conflicts!
enum NeoAssets {
  // Animations
  welcomeBackground('urn:local:animations:welcome_background:json'),

  // Icons - 16px
  arrowDown16px("urn:local:icons:arrow_down_16px:svg"),
  arrowRight16px("urn:local:icons:arrow_right_16px:svg"),
  arrowUp16px("urn:local:icons:arrow_up_16px:svg"),
  calendar16px("urn:local:icons:calendar_16px:svg"),
  check16px("urn:local:icons:check_16px:svg"),
  clock16px("urn:local:icons:clock_16px:svg"),
  close16px("urn:local:icons:close_16px:svg"),
  creditCardAdd16px("urn:local:icons:credit_card_add_16px:svg"),
  edit16px('urn:local:icons:edit_16px:svg'),
  informationCircle16px("urn:local:icons:information_circle_16px:svg"),
  plusCircle16px("urn:local:icons:plus_circle_16px:svg"),
  share16px("urn:local:icons:share_16px:svg"),
  trash16px("urn:local:icons:trash_16px:svg"),

  // Icons - 20x
  accountAdd20px('urn:local:icons:account_add_20px:svg'),
  accountTransaction20px('urn:local:icons:account_transaction_20px:svg'),
  analyticsUp20px('urn:local:icons:analytics_up_20px:svg'),
  arrowDown20px('urn:local:icons:arrow_down_20px:svg'),
  arrowRight20px('urn:local:icons:arrow_right_20px:svg'),
  arrowUp20px('urn:local:icons:arrow_up_20px:svg'),
  authorityLimits20px('urn:local:icons:authority_limits_20px:svg'),
  briefcase20px('urn:local:icons:briefcase_20px:svg'),
  bubbleChatQuestion20px('urn:local:icons:bubble_chat_question_20px:svg'),
  building20px('urn:local:icons:building_20px:svg'),
  calendarCheckOut20px('urn:local:icons:calendar_check_out_20px:svg'),
  cardActions20px('urn:local:icons:card_actions_20px:svg'),
  cardCancel20px('urn:local:icons:card_cancel_20px:svg'),
  cardTransaction20px('urn:local:icons:card_transaction_20px:svg'),
  cashAdvance20px('urn:local:icons:cash_advance_20px:svg'),
  changeScreenMode20px('urn:local:icons:change_screen_mode_20px:svg'),
  chartBreakoutSquare20px('urn:local:icons:chart_breakout_square_20px:svg'),
  check20px('urn:local:icons:check_20px:svg'),
  checkmarkCircle20px('urn:local:icons:checkmark_circle_20px:svg'),
  circlePassword20px('urn:local:icons:circle_password_20px:svg'),
  close20px('urn:local:icons:close_20px:svg'),
  coins20px('urn:local:icons:coins_20px:svg'),
  contactless20px('urn:local:icons:contactless_20px:svg'),
  creditCard20px('urn:local:icons:credit_card_20px:svg'),
  creditCardCheck20px('urn:local:icons:credit_card_check_20px:svg'),
  digitalSlip20px('urn:local:icons:digital_slip_20px:svg'),
  documentAttachment20px('urn:local:icons:document_attachment_20px:svg'),
  edit20px('urn:local:icons:edit_20px:svg'),
  error20px('urn:local:icons:error_20px:svg'),
  extract20px('urn:local:icons:extract_20px:svg'),
  eye20px('urn:local:icons:eye_20px:svg'),
  eyeSlash20px('urn:local:icons:eye_slash_20px:svg'),
  fileBlock20px('urn:local:icons:file_block_20px:svg'),
  fileSearch20px('urn:local:icons:file_search_20px:svg'),
  fileVerified20px('urn:local:icons:file_verified_20px:svg'),
  filter20px('urn:local:icons:filter_20px:svg'),
  filterRemove20px('urn:local:icons:filter_remove_20px:svg'),
  filterSelected20px('urn:local:icons:filter_selected_20px:svg'),
  home20px('urn:local:icons:home_20px:svg'),
  image20px('urn:local:icons:image_20px:svg'),
  informationCircle20px('urn:local:icons:information_circle_20px:svg'),
  keyframesDouble20px('urn:local:icons:keyframes_double_20px:svg'),
  languageSquare20px('urn:local:icons:language_square_20px:svg'),
  license20px('urn:local:icons:license_20px:svg'),
  location20px('urn:local:icons:location_20px:svg'),
  loginSquare20px('urn:local:icons:login_square_20px:svg'),
  logoutSquare20px('urn:local:icons:logout_square_20px:svg'),
  mail20px('urn:local:icons:mail_20px:svg'),
  masterCard20px('urn:local:icons:master_card_20px:svg'),
  messageDone20px('urn:local:icons:message_done_20px:svg'),
  minus20px('urn:local:icons:minus_20px:svg'),
  mobileProgramming20px('urn:local:icons:mobile_programming_20px:svg'),
  moneyReceive20px('urn:local:icons:money_receive_20px:svg'),
  notificationActive20px('urn:local:icons:notification_active_20px:svg'),
  notificationSquare20px('urn:local:icons:notification_square_20px:svg'),
  passwordTransaction20px('urn:local:icons:password_transaction_20px:svg'),
  paymentSuccess20px('urn:local:icons:payment_success_20px:svg'),
  plus20px('urn:local:icons:plus_20px:svg'),
  plusCircle20px('urn:local:icons:plus_circle_20px:svg'),
  propertyNew20px('urn:local:icons:property_new_20px:svg'),
  search20px('urn:local:icons:search_20px:svg'),
  security20px('urn:local:icons:security_20px:svg'),
  securityLock20px('urn:local:icons:security_lock_20px:svg'),
  settings20px('urn:local:icons:settings_20px:svg'),
  share20px('urn:local:icons:share_20px:svg'),
  smartPhone20px('urn:local:icons:smart_phone_20px:svg'),
  tickDouble20px('urn:local:icons:tick_double_20px:svg'),
  transport20px('urn:local:icons:transport_20px:svg'),
  trash20px('urn:local:icons:trash_20px:svg'),
  userAccount20px('urn:local:icons:user_account_20px:svg'),
  warning20px('urn:local:icons:warning_20px:svg'),

  // Icons - 24px
  account24px('urn:local:icons:account_24px:svg'),
  accountError24px('urn:local:icons:account_error_24px:svg'),
  arrowLeft24px('urn:local:icons:arrow_left_24px:svg'),
  arrowRightDouble24px('urn:local:icons:arrow_right_double_24px:svg'),
  arrowTransfer24px('urn:local:icons:arrow_transfer_24px:svg'),
  calendarSetting24px('urn:local:icons:calendar_setting_24px:svg'),
  cameraPhoto24px('urn:local:icons:camera_photo_24px:svg'),
  cancelCircle24px('urn:local:icons:cancel_circle_24px:svg'),
  cardCancel24px('urn:local:icons:card_cancel_24px:svg'),
  cashAdvance24px('urn:local:icons:cash_advance_24px:svg'),
  check24px('urn:local:icons:check_24px:svg'),
  checkList24px('urn:local:icons:check_list_24px:svg'),
  circleCheck24px('urn:local:icons:circle_check_24px:svg'),
  clock24px('urn:local:icons:clock_24px:svg'),
  close24px('urn:local:icons:close_24px:svg'),
  creditCard24px('urn:local:icons:credit_card_24px:svg'),
  creditCardAdd24px('urn:local:icons:credit_card_add_24px:svg'),
  creditCardCheck24px('urn:local:icons:credit_card_check_24px:svg'),
  creditCardStil24px('urn:local:icons:credit_card_stil_24px:svg'),
  error24px('urn:local:icons:error_24px:svg'),
  filter24px('urn:local:icons:filter_24px:svg'),
  home24px('urn:local:icons:home_24px:svg'),
  imageAdd24px('urn:local:icons:image_add_24px:svg'),
  informationCircle24px('urn:local:icons:information_circle_24px:svg'),
  insurance24px('urn:local:icons:insurance_24px:svg'),
  languageEn24px('urn:local:icons:language_en_24px:svg'),
  languageTr24px('urn:local:icons:language_tr_24px:svg'),
  license24px('urn:local:icons:license_24px:svg'),
  location24px('urn:local:icons:location_24px:svg'),
  logout24px('urn:local:icons:logout_24px:svg'),
  masterCard24px('urn:local:icons:master_card_24px:svg'),
  menu24px('urn:local:icons:menu_24px:svg'),
  nature24px('urn:local:icons:nature_24px:svg'),
  notificationActive24px('urn:local:icons:notification_active_24px:svg'),
  notificationSquare24px('urn:local:icons:notification_square_24px:svg'),
  password24px('urn:local:icons:password_24px:svg'),
  passwordError24px('urn:local:icons:password_error_24px:svg'),
  permission24px('urn:local:icons:permission_24px:svg'),
  plus24px('urn:local:icons:plus_24px:svg'),
  share24px('urn:local:icons:share_24px:svg'),
  star24px('urn:local:icons:star_24px:svg'),
  transport24px('urn:local:icons:transport_24px:svg'),
  trash24px('urn:local:icons:trash_24px:svg'),
  user24px('urn:local:icons:user_24px:svg'),
  userFill24px('urn:local:icons:user_fill_24px:svg'),
  warning24px('urn:local:icons:warning_24px:svg'),
  wrench24px('urn:local:icons:wrench_24px:svg'),

  // Icons - 32px
  star32px('urn:local:icons:star_32px:svg'),

  // Images
  cardCreditStandart('urn:local:images:card_credit_standart:png'),
  cardDebit('urn:local:images:card_debit:png'),
  cardImages('urn:local:images:card_images:png'),
  debitSuccessImage('urn:local:images:debit_success_image:svg'),
  eDevletLogo('urn:local:images:e_devlet_logo:svg'),
  gridBackground('urn:local:images:grid_background:svg'),
  largeCardImages('urn:local:images:large_card_images:png'),
  masterpassLogo('urn:local:images:masterpass_logo:svg'),
  onAppBarLogo('urn:local:images:on_app_bar_logo:svg'),
  popupIconError('urn:local:images:popup_icon_error:svg'),
  popupIconInfo('urn:local:images:popup_icon_info:svg'),
  popupIconSuccess('urn:local:images:popup_icon_success:svg'),
  popupIconWarning('urn:local:images:popup_icon_warning:svg'),
  smallCardImage('urn:local:images:small_card_image:png'),
  splashLogo('urn:local:images:splash_logo:png'),
  themeDarkImage('urn:local:images:theme_dark_image:svg'),
  themeLightImage('urn:local:images:theme_light_image:svg'),
  themeSystemImage('urn:local:images:theme_system_image:svg'),
  ;

  final String urn;

  const NeoAssets(this.urn);

  String get path => AssetUrn.fromString(urn)?.path ?? "";
}
